# Generated by Django 5.1 on 2025-11-06 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_identificacion', models.CharField(max_length=20, unique=True, verbose_name='Número de Identificación')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de la Vaca')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('raza', models.CharField(max_length=50, verbose_name='Raza')),
                ('estado_reproductivo', models.CharField(default='No gestante', max_length=50, verbose_name='Estado Reproductivo')),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Peso (kg)')),
                ('corral_actual', models.CharField(max_length=30, verbose_name='Corral Actual')),
                ('notas', models.TextField(blank=True, verbose_name='Notas de la Vaca')),
            ],
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(verbose_name='Fecha de Registro')),
                ('cantidad_litros', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Cantidad (Litros)')),
                ('turno', models.CharField(max_length=20, verbose_name='Turno')),
                ('calidad', models.CharField(max_length=100, verbose_name='Detalles de Calidad')),
                ('empleado_registro', models.CharField(max_length=100, verbose_name='Empleado que Registra')),
                ('equipo_usado', models.CharField(blank=True, max_length=100, verbose_name='Equipo Usado')),
                ('vaca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producciones', to='app_Granja_Vacas.vaca', verbose_name='Vaca asociada')),
            ],
        ),
        migrations.CreateModel(
            name='EventoSanitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(max_length=100, verbose_name='Tipo de Evento')),
                ('fecha_evento', models.DateField(verbose_name='Fecha del Evento')),
                ('tratamiento', models.TextField(verbose_name='Tratamiento Aplicado')),
                ('veterinario', models.CharField(max_length=100, verbose_name='Veterinario Responsable')),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Costo Total (€/$)')),
                ('dias_retiro', models.IntegerField(default=0, verbose_name='Días de Retiro')),
                ('vacas_afectadas', models.ManyToManyField(related_name='eventos_sanitarios', to='app_Granja_Vacas.vaca', verbose_name='Vacas Afectadas')),
            ],
        ),
    ]
