# Generated by Django 5.1 on 2025-11-10 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Granja_Vacas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventosanitario',
            name='dias_retiro',
        ),
        migrations.RemoveField(
            model_name='eventosanitario',
            name='tratamiento',
        ),
        migrations.RemoveField(
            model_name='eventosanitario',
            name='vacas_afectadas',
        ),
        migrations.AddField(
            model_name='eventosanitario',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='eventosanitario',
            name='vaca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='app_Granja_Vacas.vaca', verbose_name='Vaca atendida'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventosanitario',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Costo del Evento'),
        ),
    ]
