# Generated by Django 5.1 on 2025-11-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Granja_Vacas', '0002_remove_eventosanitario_dias_retiro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventosanitario',
            name='dias_retiro',
            field=models.IntegerField(default=0, verbose_name='Días de Retiro'),
        ),
    ]
