# Generated by Django 5.1 on 2025-11-10 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Granja_Vacas', '0003_eventosanitario_dias_retiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventosanitario',
            name='notas',
            field=models.TextField(blank=True, verbose_name='Notas adicionales'),
        ),
        migrations.AlterField(
            model_name='eventosanitario',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción del Evento'),
        ),
        migrations.AlterField(
            model_name='eventosanitario',
            name='vaca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_sanitarios', to='app_Granja_Vacas.vaca', verbose_name='Vaca asociada'),
        ),
    ]
